server:
  port: "8080"
  mode: "debug"

database:
  host: "localhost"
  port: "3306"
  username: "root"
  password: "123456"
  database: "golang_dev"

jwt:
  secret_key: "dev-secret-key-change-in-production"
  expire: 24
